language: php

php:
  - 7.2

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    
env:
  global:
    - APP_ENV: test
    - DATABASE_URL: mysql://root:@127.0.0.1:3306/test
    - SYMFONY_DEPRECATIONS_HELPER: disabled
    - JWT_SECRET_KEY: config/jwt/private.pem.test
    - JWT_PUBLIC_KEY: config/jwt/public.pem.test
    - JWT_PASSPHRASE: s$cretf0rt3st
    - JWT_TOKENTTL: 3600

services:
  - mysql

before_install:
  - composer self-update
  - cp .env.dist .env
  - cp phpunit.xml.dist phpunit.xml

install:
  - composer install
  - mysql -e 'create database test;'

before_script:
  - php bin/console doctrine:database:drop --force
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - phpunit