language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    
env:
  global:
    - APP_ENV: prod

services:
  - mysql

before_install:
  - composer self-update
  - cp .env.travis.dist .env
  - cp phpunit.xml.travis.dist phpunit.xml

install:
  - composer install
  - mysql -e 'create database test;'

before_script:
  - php bin/console doctrine:database:drop --force
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - phpunit
