sudo: required

branches:
  only:
    - develop
    - master

services:
  - docker

env:
  global:
    - PATH_APP: web/
    - APP_ENV: test
    - DATABASE_URL: mysql://db_user:db_pass@mysql:3306/db_name
    - SYMFONY_DEPRECATIONS_HELPER: disabled
    - JWT_SECRET_KEY: $PATH_APP/config/jwt/private.pem
    - JWT_PUBLIC_KEY: $PATH_APP/config/jwt/public.pem
    - JWT_PASSPHRASE: s$cretf0rt3st
    - JWT_TOKENTTL: 3600

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - cp .env.dist .env
  - cp $PATH_APP/.env.dist $PATH_APP/.env
  - cp $PATH_APP/phpunit.xml.dist $PATH_APP/phpunit.xml
  - openssl genrsa -passout pass:$JWT_PASSPHRASE -out $JWT_SECRET_KEY -aes256 4096
  - openssl rsa -pubout -in $JWT_SECRET_KEY -passin pass:$JWT_PASSPHRASE -out $JWT_PUBLIC_KEY

install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps

before_script:
  - docker-compose exec phpfpm composer self-update
  - docker-compose exec phpfpm php bin/console doctrine:database:drop --force
  - docker-compose exec phpfpm php bin/console doctrine:database:create
  - docker-compose exec phpfpm php bin/console doctrine:schema:update --force
  - docker-compose exec phpfpm php bin/console doctrine:fixtures:load --no-interaction

script:
  - docker-compose exec phpfpm phpunit tests
