language: php

php:
  - 7.2

env:
  global:
    - APP_ENV: prod
    - DATABASE_URL=mysql://travis:@127.0.0.1:3306/test

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e 'create database test'

install:
  - composer install
  - cp .env.travis.dist .env
  - cp phpunit.xml.travis.dist phpunit.xml
  - php bin/console doctrine:database:drop --force
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - phpunit
